### ISSUE TITLE
pathexplorer CSS colors are hard-coded for light theme.

### ISSUE THREAD

**Issue by ghost** [jfsicilia/obsidian-file-manager#2]
See:

![image](https://github.com/user-attachments/assets/5c55626c-fc83-4600-a79a-3e5d2228b60a)

It should be using CSS variables like `color: var(--text-normal)` to adapt to both dark and light themes.

**Comment by jfsicilia** [comment]
Now is fixed in version 1.2.1. Thanks for pointing it out!
