### ISSUE TITLE
I can install your plugin but not activate it

### ISSUE THREAD

**Issue by merlinuwe** [jfsicilia/obsidian-file-manager#3]
I can install your plugin but not activate it.

Windows 10

Obsidian 1.7.7

**Comment by jfsicilia** [comment]
Hi! What do you mean by activate it?  After enabling the plugin, if you go to the command palette, don't you find multiple commands under "File Manager". Have you tried to add a pathexplorer codeblock in a note?

**Comment by merlinuwe** [comment]
Thanks for your answer.

When I click on the switch, it switches back and gives an error message.

![image](https://github.com/user-attachments/assets/71f0d110-7e00-405c-a6ff-eadea8235a66)

**Comment by jfsicilia** [comment]
Could you please, open Obsidian Developer Tools (Ctrl + Shift + i). A new panel will show on the right hand side with the developer tools. Under the console button/tab, could you see any errors belonging to file-manager?

**Comment by merlinuwe** [comment]
After I have rebuild the vault cache a few minutes ago

![image](https://github.com/user-attachments/assets/54bf6350-f601-41ed-80cd-1e660b259638)

the problem is gone.

This is what I see: (_after_ rebuilding the vault cache):

![image](https://github.com/user-attachments/assets/b331bf5d-cd90-4f46-bee2-7ec106341bce)

**Comment by jfsicilia** [comment]
Happy to hear!

I'm closing the issue.
